apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge-server-psql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-server-psql
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: postgresql
        image: postgres:9.5.2
        env:
        - name: POSTGRES_USER
          value: EdgeServer
        - name: POSTGRES_PASSWORD
          value:
#        command:
#        - mysqld
#        - --lower_case_table_names=1
#        - --skip-ssl
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: edge-server-psql
spec:
  selector:
    app: edge-server-psql
  ports:
  - port: 5432
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-server
    spec:
      containers:
      - name: edge-server
        image: gcr.io/extreme-environments/edge-server
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://admin:admin@registry.default.svc.cluster.local:8761/eureka/
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:admin@registry.default.svc.cluster.local:8761/config
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://edge-server-psql.default.svc.cluster.local:5432/
---
apiVersion: v1
kind: Service
metadata:
  name: edge-server
spec:
  selector:
    app: edge-server
  type: LoadBalancer
  ports:
  - port: 8080
